#ifndef RIDGE_H
#define RIDGE_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#define RIDGE_N 120

enum {
    RIDGE_OK = 0,
    RIDGE_EINVAL = -1,
    RIDGE_ENUMERIC = -2,
    RIDGE_ENOTSPD = -3,
    RIDGE_ELAPACK = -4
};

/* The guard prefixes provide valid storage for the one-based pointer offsets
 * generated by f2c. Each concurrent call requires a separate workspace.
 */
typedef struct {
    float factor[RIDGE_N * RIDGE_N + RIDGE_N + 1];
    float rhs[2 * RIDGE_N + 1];
    long lapack_info;
} ridge_workspace_f32;

typedef struct {
    double factor[RIDGE_N * RIDGE_N + RIDGE_N + 1];
    double rhs[2 * RIDGE_N + 1];
    long lapack_info;
} ridge_workspace_f64;

/* X is row-major X[120][120], Y is row-major Y[rows][120], and B is
 * row-major B[rows][120]. Both functions minimize
 * ||B*X-Y||_F^2 + lambda*||B||_F^2 for lambda > 0.
 *
 * X, Y, B, and work must occupy disjoint memory. The functions do not use
 * dynamic memory and preserve X and Y. Use B only when RIDGE_OK is returned.
 */
int ridge_solve_f32(const float *x, const float *y, size_t rows,
                    float lambda, float *b, ridge_workspace_f32 *work);

int ridge_solve_f64(const double *x, const double *y, size_t rows,
                    double lambda, double *b, ridge_workspace_f64 *work);

#ifdef __cplusplus
}
#endif

#endif
