#ifndef RIDGE_H
#define RIDGE_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#define RIDGE_N 120
#define RIDGE_NORMAL_RHS 6
#define RIDGE_PACKED_SIZE (RIDGE_N * (RIDGE_N + 1) / 2)

enum {
    RIDGE_OK = 0,
    RIDGE_EINVAL = -1,
    RIDGE_ENUMERIC = -2,
    RIDGE_ENOTSPD = -3,
    RIDGE_ELAPACK = -4
};

/* The guard prefixes provide valid storage for the one-based pointer offsets
 * generated by f2c. Each concurrent call requires a separate workspace.
 */
typedef struct {
    float factor[RIDGE_PACKED_SIZE + 1];
    float rhs[2 * RIDGE_N + 1];
    long lapack_info;
} ridge_workspace_f32;

typedef struct {
    float factor[RIDGE_PACKED_SIZE + 1];
    float rhs[RIDGE_N * RIDGE_NORMAL_RHS + RIDGE_N + 1];
    long lapack_info;
} ridge_normal_workspace_f32;

/* X is row-major X[120][120], Y is row-major Y[rows][120], and B is
 * row-major B[rows][120]. The function minimizes
 * ||B*X-Y||_F^2 + lambda*||B||_F^2 for lambda > 0.
 *
 * X, Y, B, and work must occupy disjoint memory. The functions do not use
 * dynamic memory and preserve X and Y. Use B only when RIDGE_OK is returned.
 */
int ridge_solve_f32(const float *x, const float *y, size_t rows,
                    float lambda, float *b, ridge_workspace_f32 *work);

/* Returns the LAPACK lower-packed XTX construction area owned by work.
 * The corresponding solve function overwrites this area with its packed
 * Cholesky factor, so the caller must rebuild XTX before every solve.
 */
float *ridge_normal_packed_matrix_f32(ridge_normal_workspace_f32 *work);

/* Returns the zero-based LAPACK lower-packed index for a symmetric matrix.
 * row and col may be supplied in either order and must both be below RIDGE_N.
 */
size_t ridge_packed_lower_index(size_t row, size_t col);

/* XTY is row-major XTY[120][6], and coefficients is row-major
 * coefficients[120][6]. The function solves
 *
 *     (XTX + lambda*I) * coefficients = XTY
 *
 * using the packed XTX previously built in
 * ridge_normal_packed_matrix_f32(work), with one Cholesky factorization and
 * six right-hand sides. XTY is preserved.
 * coefficients is updated only after both LAPACK calls succeed.
 */
int ridge_solve_normal_f32(const float *xty, float lambda,
                           float *coefficients,
                           ridge_normal_workspace_f32 *work);

#ifdef __cplusplus
}
#endif

#endif
