#ifndef RIDGE_H
#define RIDGE_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#define RIDGE_N 120
#define RIDGE_NORMAL_RHS 6

enum {
    RIDGE_OK = 0,
    RIDGE_EINVAL = -1,
    RIDGE_ENUMERIC = -2,
    RIDGE_ENOTSPD = -3,
    RIDGE_ELAPACK = -4
};

/* The guard prefixes provide valid storage for the one-based pointer offsets
 * generated by f2c. Each concurrent call requires a separate workspace.
 */
typedef struct {
    float factor[RIDGE_N * RIDGE_N + RIDGE_N + 1];
    float rhs[2 * RIDGE_N + 1];
    long lapack_info;
} ridge_workspace_f32;

typedef struct {
    double factor[RIDGE_N * RIDGE_N + RIDGE_N + 1];
    double rhs[2 * RIDGE_N + 1];
    long lapack_info;
} ridge_workspace_f64;

typedef struct {
    double factor[RIDGE_N * RIDGE_N + RIDGE_N + 1];
    double rhs[RIDGE_N * RIDGE_NORMAL_RHS + RIDGE_N + 1];
    long lapack_info;
} ridge_normal_workspace_f64;

/* X is row-major X[120][120], Y is row-major Y[rows][120], and B is
 * row-major B[rows][120]. Both functions minimize
 * ||B*X-Y||_F^2 + lambda*||B||_F^2 for lambda > 0.
 *
 * X, Y, B, and work must occupy disjoint memory. The functions do not use
 * dynamic memory and preserve X and Y. Use B only when RIDGE_OK is returned.
 */
int ridge_solve_f32(const float *x, const float *y, size_t rows,
                    float lambda, float *b, ridge_workspace_f32 *work);

int ridge_solve_f64(const double *x, const double *y, size_t rows,
                    double lambda, double *b, ridge_workspace_f64 *work);

/* Returns the row-major XTX[120][120] construction area owned by work.
 * ridge_solve_normal_f64 overwrites this area with its Cholesky factor, so
 * the caller must rebuild XTX before every solve.
 */
double *ridge_normal_matrix_f64(ridge_normal_workspace_f64 *work);

/* XTY is row-major XTY[120][6], and coefficients is row-major
 * coefficients[120][6]. The function solves
 *
 *     (XTX + lambda*I) * coefficients = XTY
 *
 * using the XTX previously built in ridge_normal_matrix_f64(work), with one
 * Cholesky factorization and six right-hand sides. XTY is preserved.
 * coefficients is updated only after both LAPACK calls succeed.
 */
int ridge_solve_normal_f64(const double *xty, double lambda,
                           double *coefficients,
                           ridge_normal_workspace_f64 *work);

#ifdef __cplusplus
}
#endif

#endif
