#ifndef RIDGE_NEON_H
#define RIDGE_NEON_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#define RIDGE_NEON_N 120

enum {
    RIDGE_NEON_OK = 0,
    RIDGE_NEON_EINVAL = -1,
    RIDGE_NEON_ENUMERIC = -2,
    RIDGE_NEON_ENOTSPD = -3,
    RIDGE_NEON_ELAPACK = -4,
    RIDGE_NEON_EBUSY = -5
};

/* The guard prefixes provide valid storage for the one-based pointer offsets
 * generated by f2c. The busy flag rejects overlapping calls that share a
 * workspace. Place this object in static storage, not on a small RTOS stack.
 */
typedef struct {
    float factor[RIDGE_NEON_N * RIDGE_NEON_N + RIDGE_NEON_N + 1];
    float rhs[2 * RIDGE_NEON_N + 1];
    volatile unsigned int busy;
    long lapack_info;
} ridge_neon_workspace_f32;

/* X is row-major X[120][120], Y is row-major Y[rows][120], and B is
 * row-major B[rows][120]. The function minimizes
 * ||B*X-Y||_F^2 + lambda*||B||_F^2 for lambda > 0.
 *
 * X, Y, B, and work must occupy disjoint memory. The function does not use
 * dynamic memory and preserves X and Y. Use B only when RIDGE_NEON_OK is
 * returned. The caller must provide the RTOS exclusion described in README.
 */
int ridge_solve_f32_neon(const float *x, const float *y, size_t rows,
                         float lambda, float *b,
                         ridge_neon_workspace_f32 *work);

#ifdef __cplusplus
}
#endif

#endif
